from charterclub.models import Officer
from django.utils import timezone
from datetime import timedelta

o01 = Officer(netid='jarenas', year=2016, first_name='Jean-Carlos', last_name='Arenas', house_account=50.0, position='President')
o02 = Officer(netid='roryf'   , year=2016, first_name='Rory', last_name='Fitzpatrick', house_account=50.0, position='Vice President')
o03 = Officer(netid='rad3', year=2016, first_name='Robert', last_name='DeNunzio', house_account=50.0, position='Treasurer')
o04 = Officer(netid='ddore', year=2016, first_name='Daniel', last_name='Dore', house_account=50.0, position='Social Chair')
o05 = Officer(netid='msabbott'   , year=2016, first_name='Megan', last_name='Abbott', house_account=50.0, position='Kitchen Manager')
o06 = Officer(netid='cat3', year=2016, first_name='Cynthia', last_name='Tremonte', house_account=50.0, position='Kitchen Manager')
o07 = Officer(netid='kblair', year=2016, first_name='Kelsey', last_name='Blair', house_account=50.0, position='House Manager')
o08 = Officer(netid='ecblum', year=2016, first_name='Eric', last_name='Blum', house_account=50.0, position='Liquid Assets')
o09 = Officer(netid='moluo', year=2016, first_name='Mo', last_name='Luo', house_account=50.0, position='Liquid Assets')
o10 = Officer(netid='shirleyz', year=2016, first_name='Shirley', last_name='Zhu', house_account=50.0, position='Liquid Assets')
o11 = Officer(netid='hannahgm', year=2016, first_name='Hannah', last_name='Miller', house_account=50.0, position='Communications Chair')
o12 = Officer(netid='dennisds', year=2016, first_name='Dennis', last_name='Smith', house_account=50.0, position='Events Chair')
o13 = Officer(netid='dzirkel', year=2016, first_name='Daniel', last_name='Zirkel', house_account=50.0, position='Events Chair')
o14 = Officer(netid='dschen'   , year=2016, first_name='Dorothy', last_name='Chen', house_account=50.0, position='Community Service Chair / Sustainability Chair')
o15 = Officer(netid='ljkelly', year=2016, first_name='Liam', last_name='Kelly', house_account=50.0, position='Community Service Chair / Sustainability Chair')
o16 = Officer(netid='erictp', year=2016, first_name='Eric', last_name='Principato', house_account=50.0, position='Intramurals Chair')
o17 = Officer(netid='curtislb', year=2016, first_name='Curtis', last_name='Belmonte', house_account=50.0, position='Games Chair')
o18 = Officer(netid='yinaba', year=2016, first_name='Yuriko', last_name='Inaba', house_account=50.0, position='Games Chair')

o01.save()
o02.save()
o03.save()
o04.save()
o05.save()
o06.save()
o07.save()
o08.save()
o09.save()
o10.save()
o11.save()
o12.save()
o13.save()
o14.save()
o15.save()
o16.save()
o17.save()
o18.save()

m1 = Officer(netid='quanzhou', year=2015, first_name='Quan', last_name='Zhou', house_account=50.0, position='Webmaster')
m3 = Officer(netid='jwhitton', year=2016, first_name='Jeremy', last_name='Whitton', house_account=50.0, position='Webmaster')

m1.save()
m3.save()

o1 = Officer(netid='bwk', year=2015, first_name='Brian', last_name='Kernigan', house_account=0.0, position='COS 333 Professor')
o2 = Officer(netid='amytai', year=2015, first_name='Amy', last_name='Tai', house_account=0.0, position='COS 333 TA')

o1.save()
o2.save()