# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
import events.models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [(b'events', '0001_initial'), (b'events', '0002_auto_20150926_1042'), (b'events', '0003_auto_20150926_1929'), (b'events', '0004_auto_20151003_1641'), (b'events', '0005_auto_20151003_1649'), (b'events', '0006_auto_20151003_1703'), (b'events', '0007_auto_20151004_1642'), (b'events', '0008_auto_20151004_2328'), (b'events', '0009_auto_20151004_2328'), (b'events', '0010_auto_20151004_2328'), (b'events', '0011_auto_20151004_2329'), (b'events', '0012_auto_20151004_2331'), (b'events', '0013_auto_20151004_2334'), (b'events', '0014_auto_20151004_2335')]

    dependencies = [
        ('charterclub', '0001_initial'),
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('answer_text', models.CharField(max_length=255, verbose_name=b'Answer')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('guest', models.CharField(max_length=40, blank=True)),
                ('answers', models.ManyToManyField(to=b'events.Answer')),
            ],
            options={
                'ordering': ('event', 'room', 'student'),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('title', models.CharField(help_text=b'Name of the Event', max_length=255, verbose_name=b'Title')),
                ('snippet', models.TextField(help_text=b'To be displayed on the website. (Optional).', verbose_name=b'Description')),
                ('image', models.ImageField(validators=[events.models.validate_image], upload_to=b'event_images/', blank=True, help_text=b'To be displayed on the website. (Optional).', null=True)),
                ('is_points_event', models.BooleanField(default=False, help_text=b'Do Prospectives who attend get points?', verbose_name=b'Is Point Event:')),
                ('display_to_non_members', models.BooleanField(default=True, help_text=b'Are non-members allowed to see this event?', verbose_name=b'Public Event')),
                ('prospective_limit', models.IntegerField(default=0, help_text=b'set 0 to not allow prospectives. This will also hide it on the website from them (email me, Quan, to turn this feature off).', verbose_name=b'Prospectives Limit')),
                ('guest_limit', models.IntegerField(default=1, help_text=b'0 = No guests allowed. -1 = As many guests as they can.', verbose_name=b'Guest Limit')),
                ('date', models.DateField(default=datetime.datetime(2015, 9, 23, 2, 37, 1, 779496, tzinfo=utc), verbose_name=b'Date of Event')),
                ('time', models.TimeField(default=datetime.time(17, 0), help_text=b'IMPORTANT. THIS IS IN MILITARY TIME.', verbose_name=b'Time of Event')),
                ('signup_end_time', models.DateField(default=datetime.datetime(2015, 9, 23, 2, 37, 1, 779496, tzinfo=utc))),
                ('prospective_signup_start', models.DateField(default=datetime.datetime(2015, 9, 23, 2, 37, 1, 779496, tzinfo=utc), blank=True)),
                ('sophomore_signup_start', models.DateField(default=datetime.datetime(2015, 9, 23, 2, 37, 1, 779496, tzinfo=utc), blank=True)),
                ('junior_signup_start', models.DateField(default=datetime.datetime(2015, 9, 23, 2, 37, 1, 779496, tzinfo=utc), blank=True)),
                ('senior_signup_start', models.DateField(default=datetime.datetime(2015, 9, 23, 2, 37, 1, 779496, tzinfo=utc), blank=True)),
                ('signup_time', models.TimeField(default=datetime.time(17, 0), help_text=b'IMPORTANT. THIS IS IN MILITARY TIME.', verbose_name=b'Start/End  Time for signups')),
            ],
            options={
                'ordering': ('title',),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('question_text', models.CharField(max_length=255, verbose_name=b'Question Text')),
                ('help_text', models.CharField(max_length=255, verbose_name=b'Help Text', blank=True)),
                ('required', models.BooleanField(default=False)),
                ('event', models.ForeignKey(to='events.Event')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(help_text=b'Where is the Event Held?', max_length=127)),
                ('limit', models.IntegerField()),
                ('event', models.ForeignKey(related_name='event_room', to='events.Event')),
            ],
            options={
                'ordering': ('event', 'name', 'limit'),
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='entry',
            name='event',
            field=models.ForeignKey(related_name='entry_event_association', to='events.Event'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='entry',
            name='room',
            field=models.ForeignKey(related_name='entry_room_association', to='events.Room'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='entry',
            name='student',
            field=models.ForeignKey(related_query_name=b'student', related_name='event_student_association', to='charterclub.Student'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(related_name='question_answer_association', to='events.Question'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=128, verbose_name=b'Answer'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='entry',
            name='guest',
            field=models.CharField(max_length=50, blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2015, 9, 26, 14, 42, 28, 905940, tzinfo=utc), verbose_name=b'Date of Event'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='junior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 9, 26, 14, 42, 28, 905940, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='prospective_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 9, 26, 14, 42, 28, 905940, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='senior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 9, 26, 14, 42, 28, 905940, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_end_time',
            field=models.DateField(default=datetime.datetime(2015, 9, 26, 14, 42, 28, 905940, tzinfo=utc)),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='sophomore_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 9, 26, 14, 42, 28, 905940, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='event',
            name='require_rsvp',
            field=models.BooleanField(default=False, verbose_name=b'Does this event require an RSVP?'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2015, 9, 26, 23, 29, 44, 754664, tzinfo=utc), verbose_name=b'Date of Event'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='junior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 9, 26, 23, 29, 44, 754664, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='prospective_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 9, 26, 23, 29, 44, 754664, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='senior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 9, 26, 23, 29, 44, 754664, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_end_time',
            field=models.DateField(default=datetime.datetime(2015, 9, 26, 23, 29, 44, 754664, tzinfo=utc)),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='sophomore_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 9, 26, 23, 29, 44, 754664, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2015, 10, 3, 20, 41, 4, 189535, tzinfo=utc), verbose_name=b'Date of Event'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='junior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 3, 20, 41, 4, 189535, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='prospective_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 3, 20, 41, 4, 189535, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='senior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 3, 20, 41, 4, 189535, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_end_time',
            field=models.DateField(default=datetime.datetime(2015, 10, 3, 20, 41, 4, 189535, tzinfo=utc)),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='sophomore_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 3, 20, 41, 4, 189535, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2015, 10, 3, 20, 49, 44, 321031, tzinfo=utc), verbose_name=b'Date of Event'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='junior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 3, 20, 49, 44, 321031, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='prospective_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 3, 20, 49, 44, 321031, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='senior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 3, 20, 49, 44, 321031, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_end_time',
            field=models.DateField(default=datetime.datetime(2015, 10, 3, 20, 49, 44, 321031, tzinfo=utc)),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='sophomore_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 3, 20, 49, 44, 321031, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2015, 10, 3, 21, 3, 30, 206659, tzinfo=utc), verbose_name=b'Date of Event'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='junior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 3, 21, 3, 30, 206659, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='prospective_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 3, 21, 3, 30, 206659, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='senior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 3, 21, 3, 30, 206659, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_end_time',
            field=models.DateField(default=datetime.datetime(2015, 10, 3, 21, 3, 30, 206659, tzinfo=utc)),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='sophomore_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 3, 21, 3, 30, 206659, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2015, 10, 4, 20, 42, 11, 803724, tzinfo=utc), verbose_name=b'Date of Event'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='junior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 4, 20, 42, 11, 803724, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='prospective_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 4, 20, 42, 11, 803724, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='senior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 4, 20, 42, 11, 803724, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_end_time',
            field=models.DateField(default=datetime.datetime(2015, 10, 4, 20, 42, 11, 803724, tzinfo=utc)),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='sophomore_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 4, 20, 42, 11, 803724, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 28, 21, 79820, tzinfo=utc), verbose_name=b'Date of Event'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='junior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 28, 21, 79820, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='prospective_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 28, 21, 79820, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='senior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 28, 21, 79820, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_end_time',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 28, 21, 79820, tzinfo=utc)),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='sophomore_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 28, 21, 79820, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 28, 40, 761763, tzinfo=utc), verbose_name=b'Date of Event'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='junior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 28, 40, 761763, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='prospective_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 28, 40, 761763, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='senior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 28, 40, 761763, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_end_time',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 28, 40, 761763, tzinfo=utc)),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='sophomore_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 28, 40, 761763, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 28, 58, 702446, tzinfo=utc), verbose_name=b'Date of Event'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='junior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 28, 58, 702446, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='prospective_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 28, 58, 702446, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='senior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 28, 58, 702446, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_end_time',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 28, 58, 702446, tzinfo=utc)),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='sophomore_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 28, 58, 702446, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 29, 22, 609085, tzinfo=utc), verbose_name=b'Date of Event'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='junior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 29, 22, 609085, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='prospective_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 29, 22, 609085, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='senior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 29, 22, 609085, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_end_time',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 29, 22, 609085, tzinfo=utc)),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='sophomore_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 29, 22, 609085, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='event',
            name='display_to_prospectives',
            field=models.BooleanField(default=True, help_text=b'Are sophomores allowed to see this event?', verbose_name=b'Sophomore Display'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 31, 21, 735478, tzinfo=utc), verbose_name=b'Date of Event'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='junior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 31, 21, 735478, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='prospective_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 31, 21, 735478, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='senior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 31, 21, 735478, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_end_time',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 31, 21, 735478, tzinfo=utc)),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='sophomore_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 31, 21, 735478, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 34, 46, 788272, tzinfo=utc), verbose_name=b'Date of Event'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='junior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 34, 46, 788272, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='prospective_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 34, 46, 788272, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='senior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 34, 46, 788272, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_end_time',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 34, 46, 788272, tzinfo=utc)),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='sophomore_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 34, 46, 788272, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 35, 16, 187649, tzinfo=utc), verbose_name=b'Date of Event'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='junior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 35, 16, 187649, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='prospective_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 35, 16, 187649, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='senior_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 35, 16, 187649, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_end_time',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 35, 16, 187649, tzinfo=utc)),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='event',
            name='sophomore_signup_start',
            field=models.DateField(default=datetime.datetime(2015, 10, 5, 3, 35, 16, 187649, tzinfo=utc), blank=True),
            preserve_default=True,
        ),
    ]
